version: "3.8"
services:
  # api: 
  #   image: nest-todo
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres123@postgres:5432/db-nest
  #     NODE_ENV: development
  #     PORT: 3000
  #   ports:
  #     - "3000:4000"
  #   develop:
  #     watch:
  #       - action: sync+restart
  #         path: ./api
  #         target: /src/app
  #         ignore:
  #           - node_modules/
  #       - action: rebuild
  #         path: package.json
  postgres:
    image: postgres:16
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: db-nest
    networks:
      - nest-todo
networks:
  nest-todo:

